### ISSUE TITLE
Doesn't follow code styles

### ISSUE THREAD

**Issue by pjcfifa** [dmarcotte/idea-handlebars#119]
I have a default of 2 for tab size in my code styles and mustache files revert to 4 spaces per tab. Had to uninstall

**Comment by drewclauson** [comment]
I was able to get this to use 2 spaces per tab by going into Settings -> Edit -> File Types, then in the Recognized File Types list, I highlighted Handlebars/Mustache and then in the lower box, *.hbs (or whatever file extension you're using) and then I set the Template Data Language to HTML.  Because I use 2 spaces for tab size in HTML, this has works satisfactorily for me.

![image](https://cloud.githubusercontent.com/assets/10655807/13113808/bbaf3846-d55e-11e5-9f4c-b40d0a185035.png)

**Comment by pjcfifa** [comment]
Awesome, thanks
